import Header from "./components/header"; // Assuming it is a default export
import "./globals.css";
import Sidebar from "./components/sidebar"; // Assuming it is a default export
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
          rel="stylesheet"
          type="text/css"
          charset="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </head>
      <body>
        <Header /> {/* Render the header component */}
        <div className="flex w-full py-5 md:pl-14">
          <Sidebar />
          <div className="w-full  h-[88vh]  overflow-y-auto px-5 ">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
